### ISSUE TITLE
Movies in Theaters

### ISSUE THREAD

**Issue by ricardobentin** [UT-Bootcamp-Group-7/Group-Project-July-2018#19]
- [x] Random Genre Button and logic

- [x] Celebrity recommendations logic and execution

- [x] Image / Trivia

- [ ] inkblot

- [ ] YouTube - nice to have

**Comment by Traffic183** [comment]
Hey guys.  I'm still up for meeting tonight if you guys are.  
Have a bunch of stuff to show.  Will at least put in github and post links so we can look at together. 

Have a cool little movie db search page that opens into another I know wasn't on the list, but I was working through a few logic issues figured what the hell.  Also have a generator button for Daniel's pick by genre depending where he is with everything. 
celeb recommendation and inkblot quiz should both be working by the time we meet tonight. Have been this since sat class and have no idea where the days and nights have gone.  wow.

**Comment by ricardobentin** [comment]
done deal
